### ISSUE TITLE
编译1.18.X版本的Botinia源码时报错

### ISSUE THREAD

**Issue by 627977886** [gengyoubo/Public-Development-Institute#2]
编译Vazkii1.18.X版本（https://github.com/VazkiiMods/Botania/tree/1.18.x?tab=readme-ov-file）
植物魔法时，仅按照README修改了FORGE包下的build.gradle
![QQ截图20241012192955](https://github.com/user-attachments/assets/0a3d317f-6601-4866-95d8-e14a64db6f39)
用IDE编译的时候报错，报错内容如下
![QQ截图20241012192615](https://github.com/user-attachments/assets/a341f7bf-f029-4173-9f92-df90fd187bb0)
 
起因是因为Botania在1.17版本取消了光影配置的开关，并在1.19加了回来，作者提供了方法（https://github.com/VazkiiMods/Botania/commit/3658e489a88e61ba2d45ae7d730a966795392290）
但是本人实在愚钝并且连模组开发的新手都算不上，提出的问题可能比较愚蠢，还望大佬不吝赐教

**Comment by gengyoubo** [comment]
把源码发给我

**Comment by 627977886** [comment]
> 把源码发给我

通过百度网盘分享的文件：Botania-1.18.x.7z
链接：https://pan.baidu.com/s/1k1lWh0wsotARYUR2OBrn2w?pwd=qbqo 

我不清楚这样发对不对，如果不对，我会修改

这个文件我已经按照github修改了Forge/src/main/java/vazkii/botania/forge/ForgeBotaniaConfig.java、Xplat/src/main/java/vazkii/botania/client/core/helper/CoreShaders.java、Xplat/src/main/java/vazkii/botania/xplat/BotaniaConfig.java

**Comment by gengyoubo** [comment]
通过百度网盘分享的文件：新建文件夹 (2).zip
链接：https://pan.baidu.com/s/1UuQKQ5W5u7nTXk5gcjj8rA?pwd=game 
提取码：game 
--来自百度网盘超级会员V5的分享

**Comment by gengyoubo** [comment]
有问题再发评论
