### ISSUE TITLE
info.loenwind.autoconfig.factory.IRootFactory是哪个mod的

### ISSUE THREAD

**Issue by Searcher4** [gengyoubo/Public-Development-Institute#3]
我在百科诊断别人的问题时给了个我自己用来导入无curseforge的模组的方法，然后我为了确认，又试了一下runClient，但是......这次就崩了，显示末影核心试图访问这个类，但是这个类不存在，但我找遍了百科上所有loenwind制作的模组，以及有auto config这个关键词的模组，就是找不到一个叫autoconfig且和末影接口相关的模组，唯一一个叫这个名字的模组甚至都没有和末影核心相同的版本...

**Comment by Searcher4** [comment]
关闭是点错了，我以为github上禁止中文提问...我的具体问题是想知道runClient和正常运行游戏有什么性质上的出入，我的mod在正常的环境中完全可以运行，且和末影接口联动正常，但在测试环境中我的模组还没有启动，末影核心就崩溃了...
崩溃报告如下（几乎没什么营养，因为和末影核心源代码不符，末影核心没有（也不可能）在@Mod.modid(String)里面填写其他模组的名称，所以forge说末影核心谎报modid很荒谬（在我看来））
[crash-2024-10-17_01.11.17-client.txt](https://github.com/user-attachments/files/17404570/crash-2024-10-17_01.11.17-client.txt)

**Comment by gengyoubo** [comment]
能发个日志吗？

**Comment by Searcher4** [comment]
日志在这
[debug.log](https://github.com/user-attachments/files/17404604/debug.log)
[latest.log](https://github.com/user-attachments/files/17404605/latest.log)

**Comment by Searcher4** [comment]
https://github.com/SleepyTrousers/AutoConfig/tree/c399c26cc6136282a693e0b15f915b285020adb7/src/main/java/info/loenwind/autoconfig/factory
找到了，这个模组似乎不在百科上...我想办法装一下它试试会发生什么

**Comment by gengyoubo** [comment]
你试着加一下mixin
